spring:
  application:
    name: notification-messagerie

  datasource:
      url: jdbc:postgresql://switchback.proxy.rlwy.net:58642/railway
      username: postgres
      password: iFNynNNQMiaCKdnEVYeLhVEEMBHFXulW
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: messagerienotification

server:
  port: 8082
  servlet:
    context-path: /V2
  forward-headers-strategy: framework   # <-- Très important pour HTTPS derrière proxy

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: true
  packages-to-scan: org.example.notificationmessagerie.Constroller
  servers:
    - url: https://sos-mon-garage-messagerie-notification-production-5b5b.up.railway.app/V2