spring:
  application:
    name: notification-messagerie

  datasource:
    url: jdbc:postgresql://switchback.proxy.rlwy.net:58642/railway
    username: postgres
    password: iFNynNNQMiaCKdnEVYeLhVEEMBHFXulW
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: messagerienotification

server:
  port: 8089
